// Offices a client can pick when signing up. Keep in step with frontend-ts/src/data/offices.ts.
export const OFFICES = [
  "Municipal Agriculture Office",
  "Municipal Assessor's Office",
  "Municipal Budget Office",
  "Municipal Accounting Office",
  "Municipal General Services Office",
  "Municipal Civil Registrar's Office",
  "Municipal Planning and Development Office",
  "Municipal Treasurer's Office",
  "Municipal Social Welfare and Development Office",
  "Municipal Health Office",
  "Municipal Engineering Office",
  "Municipal Disaster Risk Reduction and Management Office",
  "Sangguniang Bayan Office",
  "MMO - Business Permits and Licensing Section",
  "MMO - Human Resource Management Section",
  "MMO - Tourism Section",
  "MMO - Information and Technology Section",
  "MMO - Public Employment Services Section",
  "MMO - Community Affairs Section",
  "MMO - Municipal Administrator",
  "MMO - Office of Senior Citizen Affairs",
  "SEEDO - Public Market",
  "SEEDO - Slaughterhouse",
  "Philippine National Police - Solano",
  "Bureau of Fire Protection - Solano",
  "Bureau of Jail Management and Penology - Solano",
  "Commission on Audit - LGU Solano",
  "Municipal Local Government Operations Office",
  "Department of Trade and Industry - LGU Solano",
  "Bureau of Internal Revenue - LGU Solano",
  "Municipal Agrarian Reform Office",
  "Municipal Trial Court - Solano"
] as const;
